#!/bin/sh

HASH="%C(yellow)%h%Creset"
RELATIVE_TIME="%Cgreen(%ar)%Creset"
AUTHOR="%Cblue<%an>%Creset"
REFS="%C(red)%d%Creset"
SUBJECT="%s"

FORMAT="$HASH - $RELATIVE_TIME $SUBJECT $AUTHOR $REFS"

pretty_git_log() {
    git log --graph --pretty="tformat:${FORMAT}" $* |
        # Replace (2 years ago) with (2 years)
        sed -re 's/(^[^<]*) ago\)/\1)/' |
        # Replace (2 years, 5 months) with (2 years)
        sed -re 's/(^[^<]*), [[:digit:]]+ .*months?\)/\1)/' |
        # Page only if we need to
        # -F: page only if needed
        # -X: no init
        # -R: raw control chars
        # -S: chop long lines
        less -FXRS
}
